coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  require_changes: false
  layout: "header, diff, changes, files, footer"