coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        informational: yes
    patch:
      default:
        informational: yes

comment:
  require_head: true
  layout: "header, diff, changes, files, footer"