name: Dev Changes

on:
  push:
    branches:
      - development

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Install dependencies
        run: make dev-env
      - name: Run unit tests
        run: make test Coverage=True
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage_unit_tests_report
          path: full_unit_tests.coverage

  integration:
    name: Integration tests
    runs-on: [ self-hosted, Linux ]
    container:
      image: python:3.9.18
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: make dev-env

      - name: Run integration tests
        env:
          V3IO_API: ${{ secrets.V3IO_API }}
          V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
          V3IO_FRAMESD: ${{ secrets.V3IO_FRAMESD }}
        run: make integration Coverage=True

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage_integration_report
          path: integration.coverage

  full_coverage:
    name: Full coverage
    runs-on: ubuntu-latest
    needs: [test, integration]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Install dependencies
        run: make dev-env
      - name: Download unit tests coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage_unit_tests_report
          path: . # where to download. file downloaded by name.

      - name: Download integration coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage_integration_report
          path: . # where to download. file downloaded by name.

      - name: combine coverage
        run: make coverage-combine

