name: Dev Changes Workflow

on:
  push:
    branches:
      - development

jobs:
  lint:
    name: Install requirements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Install dependencies
        run: make dev-env

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Switch to development branch
        run: git checkout development
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Install dependencies
        run: make dev-env
      - name: Run unit tests
        run: make full-coverage-unit-tests
      - name: Run integration tests
        run: make coverage-integration
      - name: Run unit tests
        run: make coverage-combine