name: Dev Changes Workflow

on:
  push:
    branches:
#      - development #TODO return it
      - local-coverage

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: pwd
        run: pwd
      - name: ls
        run: ls -lh
      - name: Install dependencies
        run: make dev-env

      - name: Run unit tests
        run: make full-coverage-unit-tests

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage_unit_tests_report
          path: full_unit_tests.coverage

  integration:
    name: Integration tests
    runs-on: [ self-hosted, Linux ]
    container:
      image: python:3.9.18
#    defaults:
#      run:
#        working-directory: /  # Set the working directory to /
    steps:
      - name: mkdir
        run: mkdir -p /home/runner/work/storey/storey
      - name: cp
        run: cp -r /__w/storey /home/runner/work/storey/storey
#      - name: Setup Symfony
#        uses: actions/checkout@v1
#        working-directory: /home/runner/work/storey/storey
      - name: pwd
        run: pwd
      - name: pwd 2
        run: pwd
        working-directory: /home/runner/work/storey/storey
      - name: ls
        run: ls -lh
      - name: ls 2
        run: ls -lh
        working-directory: /home/runner/work/storey/storey
      - name: ls 3
        run: ls -lh
        working-directory: /home/runner/work/storey
      - name: ls 4
        run: ls -lh
        working-directory: /home/runner/work/storey/storey/storey

      - uses: actions/checkout@v3
      - name: Install dependencies
        run: make dev-env
      - name: Run integration tests
        env:
          V3IO_API: ${{ secrets.V3IO_API }}
          V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
          V3IO_FRAMESD: ${{ secrets.V3IO_FRAMESD }}
        run: make coverage-integration
        working-directory: /home/runner/work/storey/storey

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage_integration_report
          path: /home/runner/work/storey/storey/integration.coverage

  full_coverage:
    name: Full coverage
    runs-on: ubuntu-latest
    needs: [test, integration]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Install dependencies
        run: make dev-env
      - name: pwd
        run: pwd
      - name: ls
        run: ls -lh

      - name: Download unit tests coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage_unit_tests_report
          path: . # where to download. file downloaded by name.

      - name: Download integration coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage_integration_report
          path: . # where to download. file downloaded by name.

      - name: Display sizes
        run:  ls -lh |grep coverage

      - name: combine coverage
        run: make coverage-combine

