name: Dev Changes Workflow

on:
  push:
    branches:
      - development

jobs:
  coverage:
    name: Full coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Switch to development branch
        run: git checkout development
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Install dependencies
        run: make dev-env
      - name: Run unit tests
        run: make full-coverage-unit-tests
      - name: Run integration tests
        env:
          V3IO_API: ${{ secrets.V3IO_API }}
          V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
          V3IO_FRAMESD: ${{ secrets.V3IO_FRAMESD }}
        run: make coverage-integration
      - name: combine coverage
        run: make coverage-combine